name: publish a snapshot

on:
  push:
    branches:
      - master
      - 'snapshot/[0-9]+.[0-9]+'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Android SDK dir
        run: echo sdk.dir=$ANDROID_HOME > local.properties
      - name: Setup JDK 8 with javah
        run: |
          echo javah=/usr/lib/jvm/zulu-8-azure-amd64/bin/javah > gradle.properties
          echo org.gradle.daemon=true > gradle.properties
          echo org.gradle.parallel=true > gradle.properties
          echo org.gradle.jvmargs=-Xmx3g -XX:MaxPermSize=2048m > gradle.properties
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: publish -PsnapshotNumber=${{ github.run_number }}
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup javah path & exclude android target
        run: |
          echo javah=C:\Program Files\Java\zulu-8-azure-jdk_8.40.0.25-8.0.222-win_x64\bin\javah > gradle.properties
          echo excludeTargets=android > gradle.properties
        shell: bash
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: hostOnlyTest
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: hostOnlyPublish -PsnapshotNumber=${{ github.run_number }}
  macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Android SDK dir
        run: echo sdk.dir=$ANDROID_HOME > local.properties
      - name: Setup JDK 8 with javah
        run: echo javah=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/javah > gradle.properties
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: hostOnlyTest
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        env:
          BINTRAY_USER: ${{ secrets.bintray_user }}
          BINTRAY_APIKEY: ${{ secrets.bintray_apikey }}
          BINTRAY_USER_ORG: ${{ secrets.bintray_user_org }}
        with:
          arguments: hostOnlyPublish -PsnapshotNumber=${{ github.run_number }}