name: test

on:
  push:
    branches-ignore:
      - master
      - '[0-9]+.[0-9]+'
      - 'snapshot/[0-9]+.[0-9]+'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/test.yml'
  pull_request:
    branches:
      - stable
      - master
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/test.yml'

jobs:
  all-native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Android SDK dir
        run: echo sdk.dir=$ANDROID_HOME > local.properties
      - name: Setup gradle.properties
        run: mv .github/conf/gradle.${{ matrix.os }} gradle.properties
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: hostOnlyTest
  universal-targets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup Android SDK dir
        run: echo sdk.dir=$ANDROID_HOME > local.properties
      - name: install default NDK for AGP
        run: $ANDROID_HOME/tools/bin/sdkmanager "ndk;21.0.6113669"
      - name: Setup gradle.properties
        run: mv .github/conf/gradle.universal gradle.properties
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
#  android:
#    runs-on: macOS-latest
#    strategy:
#      matrix:
#        api-level: [21, 23, 29]
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: 'true'
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Setup Android SDK dir
#        run: echo sdk.dir=$ANDROID_HOME > local.properties
#      - name: Setup gradle.properties
#        run: |
#          mv .github/conf/gradle.ubuntu-latest gradle.properties
#          echo javah=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/javah >> gradle.properties
#      - name: Connected Check (Android)
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: ${{ matrix.api-level }}
#          script: ./gradlew connectedCheck