name: assemble and check

on:
  push:
    branches-ignore:
      - master
      - '[0-9]+.[0-9]+'
      - 'snapshot/[0-9]+.[0-9]+'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/test.yml'
  pull_request:
    branches:
      - stable
      - master
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/test.yml'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: hostOnlyTest
  macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: hostOnlyTest
      - name: Android Instrumentation Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck